### ISSUE TITLE
只支持float，不支持double？

### ISSUE THREAD

**Issue by JianxinMa** [paulzfm/v9-cpu#3]
之前发了两条pull requests，都是和这个相关的。
如果确实是打算只支持单精度的话，就忽略那两条pull requests吧。
不过javascript并没有单精度float这种东西（可保存为32位的单精度浮点数，但是运算的时候还是会按64位的来），所以不能保证单精度float会符合IEEE 734标准。

**Comment by paulzfm** [comment]
当时把 double 支持去掉的原因是它有64位，如果需要支持的话要添加很多额外的指令，而且操作系统目前看起来不太需要支持 double，这个由软件来实现。
