### ISSUE TITLE
这个警告是什么含义：Warning: trying to write register R0

### ISSUE THREAD

**Issue by JianxinMa** [paulzfm/v9-cpu#6]
我尝试跑学弟提供的测例，然后就输出了一堆这个，请问这个warning的含义是？

**Comment by paulzfm** [comment]
R0寄存器是不让写的，因为它总是0（即 MIPS 的 zero 寄存器）

**Comment by paulzfm** [comment]
BTW，以后你在 repo 里面提问题吧：https://github.com/paulzfm/v9.js

**Comment by a1exwang** [comment]
测试样例在原来的模拟器上跑是通过的

On Jun 8, 2016 21:36, Jianxin Ma notifications@github.com wrote:

Closed #6https://github.com/paulzfm/v9-cpu/issues/6.
